version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
      include: scope

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore(deps)
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(ci)
      include: scope
