-- TuxTunes initial SQLite migration.
-- Generated by src-tauri/src/bin/gen-migration.rs.
-- Do not edit by hand; re-run the generator if the schema changes.

CREATE TABLE "preferences" (
    "key" TEXT,
    "value" TEXT NOT NULL,
    PRIMARY KEY ("key")
);

CREATE TABLE "tracks" (
    "id" INTEGER PRIMARY KEY,
    "persistent_id" TEXT UNIQUE,
    "title" TEXT NOT NULL,
    "artist" TEXT,
    "album_artist" TEXT,
    "album" TEXT,
    "composer" TEXT,
    "genre" TEXT,
    "grouping" TEXT,
    "comment" TEXT,
    "year" INTEGER,
    "track_number" INTEGER,
    "track_count" INTEGER,
    "disc_number" INTEGER,
    "disc_count" INTEGER,
    "bpm" INTEGER,
    "duration_ms" INTEGER NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "bit_rate" INTEGER,
    "sample_rate" INTEGER,
    "bit_depth" INTEGER,
    "channels" INTEGER,
    "kind" TEXT,
    "codec" TEXT,
    "replaygain_track_gain" REAL,
    "replaygain_track_peak" REAL,
    "replaygain_album_gain" REAL,
    "replaygain_album_peak" REAL,
    "dynamic_range_db" REAL,
    "file_path" TEXT NOT NULL UNIQUE,
    "file_hash" TEXT,
    "original_path" TEXT,
    "rating" INTEGER NOT NULL DEFAULT 0,
    "play_count" INTEGER NOT NULL DEFAULT 0,
    "skip_count" INTEGER NOT NULL DEFAULT 0,
    "last_played" TEXT,
    "last_skipped" TEXT,
    "loved" INTEGER NOT NULL DEFAULT 0,
    "date_added" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "date_modified" TEXT,
    "release_date" TEXT,
    "sort_title" TEXT,
    "sort_artist" TEXT,
    "sort_album" TEXT,
    "sort_album_artist" TEXT,
    "sort_composer" TEXT,
    "compilation" INTEGER NOT NULL DEFAULT 0,
    "protected" INTEGER NOT NULL DEFAULT 0,
    "purchased" INTEGER NOT NULL DEFAULT 0,
    "artwork_path" TEXT,
    "playlist_ids" TEXT NOT NULL,
    "sync_source_id" INTEGER,
    "import_status" TEXT NOT NULL DEFAULT 'ok',
    "verified_at" TEXT,
    CONSTRAINT "fk_tracks_sync_source_id" FOREIGN KEY ("sync_source_id") REFERENCES "sync_sources" ("id") ON DELETE SET NULL
);

CREATE TABLE "playlists" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "persistent_id" TEXT UNIQUE,
    "kind" TEXT NOT NULL,
    "parent_id" INTEGER,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "track_entries" TEXT NOT NULL,
    "smart_rule" TEXT,
    "cached_track_count" INTEGER NOT NULL DEFAULT 0,
    "cached_duration_ms" INTEGER NOT NULL DEFAULT 0,
    "cached_size_bytes" INTEGER NOT NULL DEFAULT 0,
    "cached_at" TEXT,
    "sync_source_id" INTEGER,
    CONSTRAINT "fk_playlists_parent_id" FOREIGN KEY ("parent_id") REFERENCES "playlists" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_playlists_sync_source_id" FOREIGN KEY ("sync_source_id") REFERENCES "sync_sources" ("id") ON DELETE SET NULL
);

CREATE TABLE "sync_sources" (
    "id" INTEGER PRIMARY KEY,
    "name" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'itunes_itl',
    "source_path" TEXT NOT NULL,
    "last_sync_at" TEXT,
    "last_sync_hash" TEXT,
    "path_mappings" TEXT NOT NULL,
    "conflict_rules" TEXT NOT NULL,
    "auto_copy_files" INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX "idx_tracks_artist" ON "tracks"("artist");

CREATE INDEX "idx_tracks_album" ON "tracks"("album");

CREATE INDEX "idx_tracks_album_artist" ON "tracks"("album_artist");

CREATE INDEX "idx_tracks_genre" ON "tracks"("genre");

CREATE INDEX "idx_tracks_rating" ON "tracks"("rating");

CREATE INDEX "idx_tracks_play_count" ON "tracks"("play_count");

CREATE INDEX "idx_tracks_date_added" ON "tracks"("date_added");

CREATE INDEX "idx_tracks_file_path" ON "tracks"("file_path");

CREATE INDEX "idx_tracks_persistent_id" ON "tracks"("persistent_id");

CREATE INDEX "idx_tracks_sync_source_id" ON "tracks"("sync_source_id");

CREATE INDEX "idx_playlists_parent_id" ON "playlists"("parent_id");

CREATE INDEX "idx_playlists_kind" ON "playlists"("kind");

CREATE INDEX "idx_playlists_sync_source_id" ON "playlists"("sync_source_id");
